# Generated by Django 5.2.5 on 2025-09-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerosol',
            name='origen',
            field=models.CharField(default='temporal', max_length=20),
            preserve_default=False,
        ),
    ]
